// notion-clone-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'notion-clone';
}

<div class="bg-gradient-to-r min-h-screen grainy from-rose-100 to-teal-100">
  <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
    <h1 class="font-semibold text-7xl text-center">
      AI <span class="text-green-600 font-bold">note taking</span> assistant.
    </h1>
    <div class="mt-4"></div>
    <h2 class="font-semibold text-3xl text-center text-slate-700">
      <app-typewriter></app-typewriter>
    </h2>
    <div class="mt-8"></div>

    <div class="flex justify-center">
      <a routerLink="/dashboard">
        <button mat-fab extended>
          Get Started
          <mat-icon>arrow_right</mat-icon>
        </button>
      </a>
    </div>
  </div>
</div>

// notion-clone-react/src/App.tsx
import React from "react";
import "./App.css";
import TypewriterTitle from "./components/TypewriterTitle";

function App() {
  return (
    <div className="bg-gradient-to-r min-h-screen grainy from-rose-100 to-teal-100">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
        <h1 className="font-semibold text-7xl text-center">
          AI <span className="text-green-600 font-bold">note taking</span>{" "}
          assistant.
        </h1>
        <div className="mt-4"></div>
        <h2 className="font-semibold text-3xl text-center text-slate-700">
          <TypewriterTitle />
        </h2>
        <div className="mt-8"></div>
      </div>
    </div>
  );
}

export default App;
