// notion-clone-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'notion-clone';
}

<div class="bg-gradient-to-r min-h-screen grainy from-rose-100 to-teal-100">
  <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
    <h1 class="font-semibold text-7xl text-center">
      AI <span class="text-green-600 font-bold">note taking</span> assistant.
    </h1>
    <div class="mt-4"></div>
    <h2 class="font-semibold text-3xl text-center text-slate-700">
      <app-typewriter></app-typewriter>
    </h2>
    <div class="mt-8"></div>

    <div class="flex justify-center">
      <a routerLink="/dashboard">
        <button mat-fab extended>
          Get Started
          <mat-icon>arrow_right</mat-icon>
        </button>
      </a>
    </div>
  </div>
</div>

// notion-clone-nextjs/src/app/page.tsx
import TypewriterTitle from "@/components/ui/TypewriterTitle";
import { Button } from "@/components/ui/button";
import { UserButton } from "@clerk/nextjs";
import { ArrowRight, Link } from "lucide-react";

export default function Home() {
  return (
    <div className="bg-gradient-to-r min-h-screen grainy from-rose-100 to-teal-100">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
        <h1 className="font-semibold text-7xl text-center">
          AI <span className="text-green-600 font-bold">note taking</span>{" "}
          assistant.
        </h1>
        <div className="mt-4"></div>
        <h2 className="font-semibold text-3xl text-center text-slate-700">
          <TypewriterTitle />
        </h2>
        <div className="mt-8"></div>

        <div className="flex justify-center">
          <Link href="/dashboard">
            <Button className="bg-green-600">
              Get Started
              <ArrowRight className="ml-2 w-5 h-5" strokeWidth={3} />
            </Button>
          </Link>
        </div>
      </div>
      <div className="h-screen">
        <UserButton afterSignOutUrl="/" />
      </div>
    </div>
  );
}
